# Generated by Django 5.2.10 on 2026-01-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('paid_amount', models.FloatField(default=0)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
            ],
        ),
    ]
